"""Schema contract tests for layer serialization boundaries."""

from pathlib import Path

import pytest

from flowscout.analysis.graph import ExplorationResult
from flowscout.codegen.scenario_tests import generate_scenario_tests
from flowscout.core.state import PageState
from flowscout.modeling.site_model import SiteModel


def _make_state(*, state_id: str, url: str) -> PageState:
    """Create a minimal valid page state fixture."""
    return PageState(
        state_id=state_id,
        url=url,
        title="Page",
        fingerprint="f" * 64,
        depth=0,
        dom_structure_hash="dom",
        visible_text_hash="text",
        form_state_hash="form",
    )


def test_exploration_to_model_round_trip_contract(tmp_path: Path) -> None:
    """Validate explore -> serialize -> model -> serialize -> generate flow."""
    result = ExplorationResult(
        config={"start_url": "https://example.com"},
        states={"s1": _make_state(state_id="s1", url="https://example.com")},
    )

    serialized_result = result.model_dump_json(indent=2)
    reloaded_result = ExplorationResult.model_validate_json(serialized_result)

    model = SiteModel.from_exploration_result(result=reloaded_result)
    assert model.schema_version == "1.0.0"
    assert model.version == "1.0.0"

    serialized_model = model.model_dump_json(indent=2)
    reloaded_model = SiteModel.model_validate_json(serialized_model)

    output_path = tmp_path / "scenario_tests.py"
    generate_scenario_tests(
        site_model=reloaded_model,
        output_path=str(output_path),
        framework="pytest",
        base_url="https://example.com",
    )

    assert output_path.exists()
    assert "Scenario-based tests generated by Flowscout site model" in (
        output_path.read_text()
    )


def test_model_builder_rejects_schema_version_mismatch() -> None:
    """Ensure incompatible ExplorationResult schema version fails clearly."""
    result = ExplorationResult(
        schema_version="0.9.0",
        version="0.9.0",
        states={"s1": _make_state(state_id="s1", url="https://example.com")},
    )

    with pytest.raises(
        ValueError,
        match="Unsupported ExplorationResult schema_version",
    ):
        SiteModel.from_exploration_result(result=result)


def test_model_builder_rejects_version_mismatch() -> None:
    """Ensure version and schema_version stay aligned."""
    result = ExplorationResult(
        schema_version="1.0.0",
        version="0.9.0",
        states={"s1": _make_state(state_id="s1", url="https://example.com")},
    )

    with pytest.raises(
        ValueError,
        match="ExplorationResult version mismatch",
    ):
        SiteModel.from_exploration_result(result=result)


def test_model_builder_requires_states() -> None:
    """Ensure required layer-1 state payload is validated."""
    result = ExplorationResult(
        schema_version="1.0.0",
        version="1.0.0",
        states={},
    )

    with pytest.raises(
        ValueError,
        match="missing required field data: states",
    ):
        SiteModel.from_exploration_result(result=result)
