"""Test generation from site model scenarios — always uses POM classes."""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from flowscout.analysis.site_model import SiteModel
from flowscout.codegen.page_objects import _catalog_to_class_name
from flowscout.smart.scenarios import FlowScenario


def generate_scenario_tests(
    site_model: SiteModel,
    output_path: str,
    *,
    framework: str = "pytest",
    base_url: str = "",
) -> str:
    """Generate test file from site model scenarios.

    POM classes must be generated first (via generate_page_objects).
    Generated tests import and use POM classes for all interactions.

    Args:
        site_model: The SiteModel with page_types, navigation_edges, scenarios.
        output_path: Path to write the generated test file.
        framework: "pytest" for Python or "playwright" for TypeScript.
        base_url: Base URL for navigation.

    Returns:
        Path to the generated test file.
    """
    # Build mapping: page_type_id → POM class name + module name
    pom_map = _build_pom_map(site_model)

    # Build mapping: page_type_id → PageType (for URLs)
    pt_map = {pt.page_type_id: pt for pt in site_model.page_types}

    if framework == "pytest":
        content = _generate_pytest(site_model, pom_map, pt_map, base_url)
    else:
        content = _generate_playwright_test(site_model, pom_map, pt_map, base_url)

    Path(output_path).write_text(content)
    return output_path


# ---------------------------------------------------------------------------
# POM mapping
# ---------------------------------------------------------------------------


class _PomInfo:
    """POM class metadata for a page type."""

    def __init__(self, class_name: str, module_name: str, var_name: str) -> None:
        self.class_name = class_name
        self.module_name = module_name
        self.var_name = var_name


def _build_pom_map(site_model: SiteModel) -> dict[str, _PomInfo]:
    """Map page_type_id → POM class info."""
    pom_map: dict[str, _PomInfo] = {}

    for pt in site_model.page_types:
        if not pt.catalog.entries:
            continue

        class_name = _catalog_to_class_name(pt.catalog)
        module_name = _to_snake_case(class_name)
        var_name = _to_var_name(class_name)
        pom_map[pt.page_type_id] = _PomInfo(class_name, module_name, var_name)

    return pom_map


def _to_snake_case(name: str) -> str:
    result = re.sub(r"(?<!^)(?=[A-Z])", "_", name)
    return result.lower()


def _to_var_name(class_name: str) -> str:
    """Convert PascalCase class name to a short variable name."""
    # MovieListingPage → listing, MovieDetailPage → detail
    # Remove "Page" suffix, take last meaningful word
    name = class_name.removesuffix("Page")
    words = re.findall(r"[A-Z][a-z]*", name)
    if words:
        return words[-1].lower()
    return _to_snake_case(name).replace("_", "")


def _sanitize_test_name(text: str) -> str:
    """Convert text to a valid test function name."""
    clean = re.sub(r"[^\w\s]", "", text.lower())
    clean = re.sub(r"\s+", "_", clean.strip())
    clean = re.sub(r"_+", "_", clean).strip("_")
    return clean[:60]


# ---------------------------------------------------------------------------
# Pytest generation
# ---------------------------------------------------------------------------


def _generate_pytest(
    site_model: SiteModel,
    pom_map: dict[str, _PomInfo],
    pt_map: dict[str, Any],
    base_url: str,
) -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines: list[str] = [
        '"""Scenario-based tests generated by Flowscout site model.',
        "",
        f"Generated: {timestamp}",
        f"Base URL: {base_url}",
        '"""',
        "",
        "import re",
        "",
        "import pytest",
        "from playwright.sync_api import Page, expect",
        "",
    ]

    # Import POM classes
    imported: set[str] = set()
    for pom in pom_map.values():
        if pom.class_name not in imported:
            lines.append(f"from pages.{pom.module_name} import {pom.class_name}")
            imported.add(pom.class_name)

    if imported:
        lines.append("")
        lines.append("")

    # Group scenarios by priority for ordering
    priority_order = {"critical": 0, "important": 1, "nice-to-have": 2}
    sorted_scenarios = sorted(
        site_model.test_scenarios,
        key=lambda s: priority_order.get(
            s.priority if isinstance(s, FlowScenario) else s.get("priority", "important"),
            1,
        ),
    )

    # Group scenarios by template for class organization
    template_groups: dict[str, list[Any]] = {}
    for scenario in sorted_scenarios:
        if isinstance(scenario, FlowScenario):
            template = scenario.template or "general"
        else:
            template = scenario.get("template", "general")
        template_groups.setdefault(template, []).append(scenario)

    used_names: set[str] = set()

    for template, scenarios in template_groups.items():
        class_name = "".join(w.capitalize() for w in template.split("_")) + "Tests"
        lines.append(f"class Test{class_name}:")
        lines.append(f'    """Tests from {template} template."""')
        lines.append("")

        for scenario in scenarios:
            sc = scenario if isinstance(scenario, FlowScenario) else FlowScenario.model_validate(scenario)

            func_name = _sanitize_test_name(sc.name)
            if func_name in used_names:
                func_name = f"{func_name}_{sc.scenario_id.split('-')[-1]}"
            used_names.add(func_name)

            lines.append(f"    def test_{func_name}(self, page: Page) -> None:")
            lines.append(f'        """{sc.description}')
            lines.append("")
            lines.append(f"        Priority: {sc.priority}")
            if sc.tags:
                lines.append(f"        Tags: {', '.join(sc.tags)}")
            lines.append('        """')

            # Generate step code
            _generate_pytest_steps(lines, sc, pom_map, pt_map, base_url)

            lines.append("")

        lines.append("")

    return "\n".join(lines)


def _generate_pytest_steps(
    lines: list[str],
    scenario: FlowScenario,
    pom_map: dict[str, _PomInfo],
    pt_map: dict[str, Any],
    base_url: str,
) -> None:
    """Generate pytest step code for a scenario."""
    instantiated: set[str] = set()

    for step in scenario.steps:
        pom = pom_map.get(step.page_type)
        pt = pt_map.get(step.page_type)

        if step.action_type == "navigate" and pom:
            # Instantiate POM and navigate
            if pom.var_name not in instantiated:
                lines.append(
                    f"        {pom.var_name} = {pom.class_name}(page)"
                )
                instantiated.add(pom.var_name)
            lines.append(f"        {pom.var_name}.navigate()")

        elif step.action_type == "fill" and step.target_selector:
            # Fill input — use POM search method if it's a search step
            if pom and "search" in step.action_description.lower():
                if pom.var_name not in instantiated:
                    lines.append(
                        f"        {pom.var_name} = {pom.class_name}(page)"
                    )
                    instantiated.add(pom.var_name)
                value = step.input_value or "test query"
                lines.append(
                    f'        {pom.var_name}.search("{value}")'
                )
            else:
                sel = step.target_selector.replace('"', '\\"')
                value = step.input_value or "test input"
                lines.append(
                    f'        page.fill("{sel}", "{value}")'
                )

        elif step.action_type == "click" and pom:
            if pom.var_name not in instantiated:
                lines.append(
                    f"        {pom.var_name} = {pom.class_name}(page)"
                )
                instantiated.add(pom.var_name)

            if step.target_selector:
                sel = step.target_selector.replace('"', '\\"')
                lines.append(
                    f'        page.click("{sel}")'
                )
            elif "item" in step.action_description.lower() or "detail" in step.action_description.lower():
                lines.append(
                    f"        {pom.var_name}.select_item(0)"
                )
            else:
                lines.append(
                    f"        # {step.action_description}"
                )

        elif step.action_type == "submit_form":
            lines.append(
                "        # Submit form (press Enter or click submit button)"
            )
            lines.append(
                '        page.keyboard.press("Enter")'
            )

        elif step.action_type is None and step.expected_outcome:
            # Verification step
            if pom and pom.var_name in instantiated:
                if pt and pt.url_pattern:
                    pattern = pt.url_pattern.replace("\\", "\\\\")
                    lines.append(
                        f'        expect(page).to_have_url(re.compile(r"{pattern}"))'
                    )
                else:
                    lines.append(
                        f"        # Verify: {step.expected_outcome}"
                    )
            else:
                lines.append(
                    f"        # Verify: {step.expected_outcome}"
                )
        else:
            lines.append(f"        # {step.action_description}")


# ---------------------------------------------------------------------------
# Playwright Test (TypeScript) generation
# ---------------------------------------------------------------------------


def _generate_playwright_test(
    site_model: SiteModel,
    pom_map: dict[str, _PomInfo],
    pt_map: dict[str, Any],
    base_url: str,
) -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines: list[str] = [
        "// Scenario-based tests generated by Flowscout site model",
        f"// Generated: {timestamp}",
        f"// Base URL: {base_url}",
        "",
        "import { test, expect } from '@playwright/test';",
        "",
    ]

    # Import POM classes
    imported: set[str] = set()
    for pom in pom_map.values():
        if pom.class_name not in imported:
            kebab = re.sub(r"(?<!^)(?=[A-Z])", "-", pom.class_name).lower()
            lines.append(
                f"import {{ {pom.class_name} }} from './pages/{kebab}';"
            )
            imported.add(pom.class_name)

    if imported:
        lines.append("")

    # Group scenarios
    priority_order = {"critical": 0, "important": 1, "nice-to-have": 2}
    sorted_scenarios = sorted(
        site_model.test_scenarios,
        key=lambda s: priority_order.get(
            s.priority if isinstance(s, FlowScenario) else s.get("priority", "important"),
            1,
        ),
    )

    template_groups: dict[str, list[Any]] = {}
    for scenario in sorted_scenarios:
        if isinstance(scenario, FlowScenario):
            template = scenario.template or "general"
        else:
            template = scenario.get("template", "general")
        template_groups.setdefault(template, []).append(scenario)

    for template, scenarios in template_groups.items():
        lines.append(f"test.describe('{template}', () => {{")
        lines.append("")

        for scenario in scenarios:
            sc = scenario if isinstance(scenario, FlowScenario) else FlowScenario.model_validate(scenario)

            lines.append(f"  test('{sc.name}', async ({{ page }}) => {{")
            _generate_ts_steps(lines, sc, pom_map, pt_map, base_url)
            lines.append("  });")
            lines.append("")

        lines.append("});")
        lines.append("")

    return "\n".join(lines)


def _generate_ts_steps(
    lines: list[str],
    scenario: FlowScenario,
    pom_map: dict[str, _PomInfo],
    pt_map: dict[str, Any],
    base_url: str,
) -> None:
    """Generate TypeScript step code."""
    instantiated: set[str] = set()

    for step in scenario.steps:
        pom = pom_map.get(step.page_type)
        pt = pt_map.get(step.page_type)

        if step.action_type == "navigate" and pom:
            if pom.var_name not in instantiated:
                lines.append(
                    f"    const {pom.var_name} = new {pom.class_name}(page);"
                )
                instantiated.add(pom.var_name)
            lines.append(f"    await {pom.var_name}.navigate();")

        elif step.action_type == "fill" and step.target_selector:
            if pom and "search" in step.action_description.lower():
                if pom.var_name not in instantiated:
                    lines.append(
                        f"    const {pom.var_name} = new {pom.class_name}(page);"
                    )
                    instantiated.add(pom.var_name)
                value = step.input_value or "test query"
                lines.append(f"    await {pom.var_name}.search('{value}');")
            else:
                sel = step.target_selector.replace("'", "\\'")
                value = step.input_value or "test input"
                lines.append(f"    await page.fill('{sel}', '{value}');")

        elif step.action_type == "click" and pom:
            if pom.var_name not in instantiated:
                lines.append(
                    f"    const {pom.var_name} = new {pom.class_name}(page);"
                )
                instantiated.add(pom.var_name)
            if step.target_selector:
                sel = step.target_selector.replace("'", "\\'")
                lines.append(f"    await page.click('{sel}');")
            elif "item" in step.action_description.lower() or "detail" in step.action_description.lower():
                lines.append(f"    await {pom.var_name}.selectItem(0);")
            else:
                lines.append(f"    // {step.action_description}")

        elif step.action_type == "submit_form":
            lines.append("    await page.keyboard.press('Enter');")

        elif step.action_type is None and step.expected_outcome:
            if pt and pt.url_pattern:
                pattern = pt.url_pattern.replace("\\", "\\\\")
                lines.append(
                    f"    await expect(page).toHaveURL(/{pattern}/);"
                )
            else:
                lines.append(f"    // Verify: {step.expected_outcome}")
        else:
            lines.append(f"    // {step.action_description}")
