---
name: CI

"on":
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  quality:
    permissions:
      contents: read
      packages: read
      pull-requests: write
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-quality.yml@b4f2df1506004eacddb6b303f235cf568050ff0e
    with:
      tooling-ref: "b4f2df1506004eacddb6b303f235cf568050ff0e"
