---
name: CI

"on":
  pull_request:
    branches: [main]
  push:
    branches: [main]
  merge_group:

jobs:
  quality:
    permissions:
      contents: read
      packages: read  # pull lintro-image from GHCR in reusable-quality-lint
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-quality-lint.yml@443a687caa93b3afa306a066aae8d8a2b4e60c3c  # v0.59.0
    with:
      tooling-ref: "443a687caa93b3afa306a066aae8d8a2b4e60c3c"  # v0.59.0
      job-name: "🛠️ Lintro Code Quality"
